### ISSUE TITLE
Look into using renv for R package maintenance 

### ISSUE THREAD

**Issue by rabutler-usbr** [usbr/MTOM#104]
At one point we explored using packrat, which never seemed to work as intended. renv is supposed to be an improved replacement for packrat. I think with the MTOM testing tool, it might be important to ensure we are all using the same R libraries. This could help with that. I can look into this in the next few weeks. 

cc: @cfelletter @sbaker2423

**Comment by cfelletter** [comment]
Sounds good, I'm a little gun shy after packrat but we can try it if your initial testing looks good.

**Comment by cfelletter** [comment]
Did you and @sbaker2423  try it out @rabutler-usbr ? (cleaning up old emails)

**Comment by rabutler-usbr** [comment]
I haven’t yet. Hopefully this week or next week

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cfelletter** [comment]
Should we implement this @rabutler-usbr ? Seems to work well for CRSS

**Comment by rabutler-usbr** [comment]
Now at https://github.com/usbr/CRMMS/issues/21
