### ISSUE TITLE
Lower Basin Hydrologic Demand Variability Inconsistency

### ISSUE THREAD

**Issue by stighi** [usbr/MTOM#118]
When we want it to fire and under what conditions?
Currently there is LBDV for: 
1. Ag users below Parker based on inflows below Parker (Impacts CAP & MWD)
2. SNWA based on inflows above Hoover
3. MWD based on Sac WY Index
Logic is inconsistent on when it fires (only normal condition, or surplus/shortage? First month of first year only, or first 3 months of first year?, etc)

**Comment by apivarnik** [comment]
4.	Rework SNWA demand variability rule. Rule will currently fail in RC 4 because SNWP pumping in mead is set as a higher priority in RC3. Should this just set a demand variability factor and not diversions?

**Comment by stighi** [comment]
@apivarnik is this done? Can we close this issue?

**Comment by stighi** [comment]
From issue #28:  Since issue 28 was created there have been numerous changes to LBDV. This was the original note for the issue:

Should below Parker Ag user hydrologic driven demand variability in year 1 of the run in months other than January?

We currently allow for CAP and SNWA demand variability in months (all months or specific months?-need to consult stakeholders) other than January - but not MWD or Ag users below Parker
