### ISSUE TITLE
CBRFC_EnsembleForecast Plot Labels

### ISSUE THREAD

**Issue by cfelletter** [usbr/MTOM#12]
I was reviewing the April run and I noticed that the plot on the Comparison sheet of  CBRFC_EnsembleForecast doesn't have 2011-2015 labeled in the legend above the plot. It's an easy fix so I'll go ahead and do it.

**Comment by clhorner** [comment]
Good catch, thanks for taking care of that!

**Comment by cfelletter** [comment]
keyword must precede issue number, so I should have said "fixed #12"
