### ISSUE TITLE
Powell.Outflow - abort due to max executions

### ISSUE THREAD

**Issue by sbaker2423** [usbr/MTOM#121]
This is an issue I've seen come to light a couple times while running hindcasts through the MTOM testbed. Currently, I'm seeing this error in a May 2019 run with ESP trace 13, RC3 in Aug 2022. MTOM is trying to solve for Powell outflow for WY 2023 which is UEB with an April adjustment to EQ. TARV is set to 15.5 maf, which cant be released by the end of the WY. The rule is going back and forth between two June outflows/carry over calculated for the WY. [e.g. June rel 1,750,426 maf = 1,351,800 maf carryover; Rel 1,752,648 = 1,349,582 carryover].

The issue seems to be in the function CalculatePowellUEBToEqualizePowellMonRel(). The MaxGeneratorRelease is determined by looking at the Powell.Peak Flow[CurrentDate] instead of estimating the value inside the function based on the calculated head being estimated based on the current release. In the WITH statement before this, the PowerPlantHeadRow is calculated but never used. Maybe this was thought through but never completed when writing the function.
It seems like the way to fix this would be to estimate the Peak Flow for the current timestep inside this function. RiverWare documentation does not have details on how this is calculated based on the available slots, so we may need to reach out to get more information. 

This doesnt seem to be a pressing issue, but it comes up every once in a while, so it would be nice to get a fix for this issue. 

[errorFiles.zip](https://github.com/usbr/MTOM/files/4547474/errorFiles.zip)

**Comment by sbaker2423** [comment]
I reached out to CADSWES to get some input on this issue. David was able to help find a fix. We will likely replace the Powell.Peak Flow slot with a RPL function getMaxReleaseGivenInflow(). The current version of this function in RW is working incorrectly. It is using a Pool Elevation value from the slot on the workspace, which is not updated in the loop, and is only returning flow for 1 turbine (?). This will be fixed in a new version of RiverWare. 
David tested the proposed fix and it computed as desired. We'll have to wait on a patch to RW to get this working in MTOM.

**Comment by rabutler-usbr** [comment]
So it is a combination of updating functions and using a new RW version?

**Comment by sbaker2423** [comment]
Yup, the function in the current RW is not working correctly (only accounting for one turbine I think). This should be fixed in the patch release. Then we need to change the Peak Flow call in the functions since this slot was the reason for the model aborting. David said he'd tested this and it had fixed the issue. I still want to double check this with some runs with the testbed though.

**Comment by rabutler-usbr** [comment]
good plan

**Comment by sbaker2423** [comment]
This issue never got resolved in the MTOM ruleset. CADSWES helped us figure out how to fix this. Calls to Powell.Peak Outflow need to be changed to the function 'GetMaxReleaseGivenInflow' so that max iterations at Powell are not exceeded. 

These changes need to be made in the 'CalculatePowellUEBToEqualizePowellMonRel' function. I'm picking this issue back up to get the changes incorporated into the ruleset.
![hajjhdjifampgfio](https://user-images.githubusercontent.com/18153871/92659811-54dd9980-f2b6-11ea-8e3f-7ec868ae62b5.png)
