### ISSUE TITLE
Remove dates from README

### ISSUE THREAD

**Issue by rabutler-usbr** [usbr/MTOM#123]
Do you think we could remove the following two lines from the 0.ReadMe.txt file:

> MTOM Model Run Date: Feb-2020
> MTOM Distribution Date: Feb-2020

I don't think it is all that useful given the file naming convention we are following, the GitHub releases, etc. and it is easy to not remember to update it.

**Comment by stighi** [comment]
I'm fine with removing the dates of the run and distribution. Especially since we include the release notes and assumptions, that information will be included in the write-up since it gets reviewed fairly extensively before release.

**Comment by apivarnik** [comment]
Just removed them from the branch I am currently working on. Will be incorporated when I merge my branch for the May run
