### ISSUE TITLE
Convergence constraint for reservoirs

### ISSUE THREAD

**Issue by sbaker2423** [usbr/MTOM#144]
Based on a RW bug, we have talked about changing the convergence constrain of reservoirs to 1e-4. I am not sure if this has been done yet, but I wanted to add this as an issue so I could attach a conversation about how this relates to Powell pool elevation. This is not a pressing issue, but I want to document it here.

In a run in the testbed, I found that Powell was reaching max iterations causing MTOM to abort. After some digging, I reached out to CADSWES about this issue and their fix was to add convergence criteria to Powell PE. The issue is summarized, followed by part of the email string with CADSWES... In testing, I found that for this specific run, the Powell PE convergence needed to be 1e-3% and 1e-4% was too small. 

-----
Issue summary:
The MTOM run with the current issue starts in Jan 2002 and runs out for 5 years. The error causing the abort is happening in the timestep Aug 2002 in run cycle 4 while RW is solving for WY 2003 equalization release from Powell (outflow is solved for in August of the previous year except at the start timestep). The loop of the execution is Powell Outflow is solved (rule 82), which causes Mead Outflow to resolve (Rule 137) and Mexico Excess to resolve (Rule 131), then the rules go back and solve the Powell Outflow rule (82). Each loop resets Powell outflow for April and August 2003. This causes Powell’s pool elevation to resolve in April 2003 to the end of the run, which then puts the Powell Outflow rule (82) back on the agenda.  The only place I see that Powell Pool elevation is used in Rule 82 is to get the initial pool elevation for Sept 30, 2002. The function this is happening in is **‘CalculatePowellUEBToEqualizePowellMonRel’.**

------
Response from CADSWES:
On 12/30/2020, Mitch Clement wrote:

Hi Sarah,
I have been looking at this some more. The only way I have found to address it so far is to change the convergence tolerance on Powell Pool Elevation. I noticed that Pool Elevation and Storage both have a convergence tolerance of 0%, and Outflow, Turbine Release and Spill use the default convergence of 0.01%. We typically recommend a small, non-zero convergence on Pool Elevation, and in some cases, None on the flows. I changed the Pool Elevation convergence to absolute 0.005 (m), and the run succeeded. I was able to reduce it to 0.004 (m) and still have the run succeed, but any smaller, and it failed. Do you know if there was a reason the convergence was set to 0% for Pool Elevation and Storage?

Once the convergence on Pool Elevation is increased slightly, the max release calculation for August is the same for successive rule executions rather than alternating between two values. 

--
On 12/29/2020, Mitch Clement wrote:
Sarah,
I have been able to zero in on what is causing the max iterations error, but I do not yet have a fix.

The issue is really limited to rule 82. Although it causes rules 137 and 131 to re-execute each time, they are not involved in the issue. Rule 82 alternates between two sets of outflows because the logic alternates between two Powell max release values for August 2003. The CalculatePowellUEBToEqualizePowellMonRel function first allocates the annual volume to each month using a base pattern. For each month, it limits this preliminary value to be no more than the max release calculated by the GetMaxReleaseGivenInflow pre-defined function. In August, it is limited by the max release. Then it make a second pass to check if the full annual volume was allocated. In this case, the full volume was not yet allocated because August, as well as May and September were limited by max release. So it tries to add the remaining volume to any months in April through September that have remaining capacity before reaching their max release. It is able to allocate all of the remaining volume to April. The Power object goes ahead and solves. The new Pool Elevation values cause rule 82 to execute again. This time it has the same base pattern but calculates a different max release for August, which means a different amount of additional flow gets placed on April. The object re-solves, calculating new Pool Elevations, which trigger rule 82 to execute again. This time it calculates the same August max release that it did the first time, so the April volume is the same as the first time, and it starts alternating between the two states until it hits max iterations. 

I am not sure why the May and September max release calculations remain the same on all iterations, but the August max release changes. The Pool Elevations change on all of those timesteps. I will need to give some more thought to what needs to be done to address this issue.

**Comment by sbaker2423** [comment]
This is a slightly different issue, but I'm now seeing instances where MTOM is not releasing exactly the TARV due to a smaller convergence constraint. When Powell has to iterate on an outflow, it's release is sometime s ~50 acre-ft off. Setting a smaller convergence constraint on Powell.Outflow would fix this. Let's discuss at the next MTOM dev team meeting.

**Comment by hpatno** [comment]
Hi @sbaker2423 This is a good discussion item. Based on the email from Mitch, it looks like setting convergence to 0 on flow slots is recommended, and your assessment is that it would fix the issue. We can talk further on the next call.

**Comment by sbaker2423** [comment]
All convergence criteria has been set to 1x10^-4. No changes need to be made at this time.
