### ISSUE TITLE
UB DO Reporting

### ISSUE THREAD

**Issue by cfelletter** [usbr/MTOM#151]
Malcolm/Jim thinks we should be providing MTOM/CRSS results with instance of DO reported more explicitly.
We currently have Powell % of traces less than 3525 in any year. Could we add CRSS's forecasting equations to MTOM to create a Powell Deficit Volume/Flag which we could then report via a "Upper Basin: Percent of Traces with UB Drought Operations"  

Regression equations developed to estimate the inflow into Powell through the following April should be valid to use in MTOM/they aren't CRSS specific. Please correct me if I'm wrong @rabutler-usbr or @hpatno    

---
CRSS Process to Adapt: 
Currently in April and August the model projects the elevation at Lake Powell for March 31 of the following year using these steps:

1. Estimate Powell's release through the next April (P_O^est). Powell's forecast release through September (existing CRSS ForecastPowellRelease function) + a constant that is determined from the following table:

Condition	Constant (maf)
In mid-elevation release tier, and Mead’s previous EOCY elevation > 1,025 ft.	3.58
In mid-elevation release tier, and Mead’s previous EOCY elevation < 1,025 ft.	4.00
In lower elevation balancing tier, and Powell EOWY storage forecast > Mead EOWY storage forecast	4.15
In lower elevation balancing tier, and Powell EOWY storage forecast < Mead EOWY storage forecast	3.28
All other condtions	4.00

2. Estimate the inflow into Powell through the following April. Regression equations were developed through analyses of the April and August 24-Month Studies from 1994-2013. The estimation is intended to mimic forecasts by correlating errors and observed magnitudes of inflow. 
	
3. Compute the "deficit volume" (DV):
DV=Powell.Storage[@""t-1\"" ]+P_I^est-Evap-P_O^est-PE

Evap is an estimate of evaporation through March 31.
PE is the protection elevation of 3,525 feet converted to a volume, which equals 5,926,576 acre-ft. 

4. If DV is negative, then a "deficit volume" exists, and drought operations begin, or continue.

**Comment by rabutler-usbr** [comment]
The equations are not CRSS specific as they are derived from errors in the 24-MS. 

But - for step 2, do we even need to use those regressions? We are using forecasts in MTOM and b/c of the Run Cycles we know the inflow to Powell for the entire simulation horizon. I spin myself into a confusing rabbit hole pretty quickly on this. 
- CRSS is trying to mimic forecast error by adjusting the natural flows, instead of using perfect knowledge for each trace
    - the forecast error is based on the errors associated with the most probable forecast 
- MTOM is using a forecast (35 forecasts)
- Does it make sense to adjust each one of those forecasts based on errors associated with the most probable forecast?
- Or should we treat each trace as a forecast with errors already embedded in it, and compute the deficit volume based on those without any other adjustments?
    - this might make it easier to make forecasts of more than March 1 elevations or in months besides April and August.

**Comment by cfelletter** [comment]
Oh this does make my brain hurt. I can see arguments for and against. Our goal of driving MTOM with forecasts is to simulate a range of future hydrologic conditions and get a range of operations associated with each condition. I think by using the inflow to Powell calculated in Run Cycle 2 you could each month look forward 24 months and project Powell PEs (no need for regressions). If in any of those months the projected PE is < 3525 you flag that DO would commence. In subsequent months this flag isn't very useful because the model isn't simulating DO and therefore doesn't know when DO would end. But this would give you a yearly # of traces which have triggered DO that year or previously. E.g.
2022 - 0 traces, 2023 - 3 traces, 2024 - 9 traces
Looking at how this changes with new forecasts in a 5 year table would be a useful way to track the increasing risk of having to initiate DO.

**Comment by rabutler-usbr** [comment]
Yeah the approach you describe above seems to make sense to me. Do we even need to project forward or can we not use the Powell elevations that are the "final answers". If we aren't actually implementing DO, then we are just reporting: if each trace was a most probable forecast, these are the number of traces that would need to implement DO.

**Comment by cfelletter** [comment]
Glad we are in accord. @stighi,  Alan and I propose a new output flag for UB DO triggerings be added to MTOM and reported. I can explain at our next meeting but the background is above.  I think it could be done without impacting other modeling results. Should I move a test copy into the model prior to our next meeting so it can be part of the February run or hold off till March?

**Comment by cfelletter** [comment]
We should first solicit stakeholder feedback on if such a metric is useful before releasing results. Jim expressed some concerns about if this would too confusing or not what the UD states are looking for. I'd be happy to draft something we could send out to the pilot group to get feedback on.

**Comment by stighi** [comment]
There currently are 2 expression slots that identify if the Powell elevation is below 3525.
PowellData.PowellBelow3525 is a monthly flag that has 1 if the elevation  is below 3525 and 0 otherwise.
PowellData.PowellBelow3525_Annual is a yearly flag that has 1 if the elevation went below 3525 in any month during the year, and 0 otherwise.

If you want to use these slots for reporting, you can do so. These flags are included in the Excel output DMI for use in the Excel output visualization app.

**Comment by cfelletter** [comment]
@stighi Yes I remember adding these to the output. I think the nuance is that we want the flag to be set in the first month were in the next 24 months the forecasted, not actual, PE is below 3525.  This is the point we'd initiate DO, not when Powell fell to 3525. This 'forecast' would be based on the actual computed inflow (we are treating the cycle 2 UB solution as the 24 MS Most)  and an estimated Powell release and evaporation.

**Comment by cfelletter** [comment]
Tabled in favor of enhancing modeling capabilities in CRSS. One consideration was CRSS is official 2-5 year projection. A determination of if CRSS or MTOM was greater skill in years 2-5 is underway.
