### ISSUE TITLE
Powell Elevation Area Table inconsistent with CRSS

### ISSUE THREAD

**Issue by sbaker2423** [usbr/MTOM#153]
MTOM's Powell Elevation Area Table does not match the table in CRSS. We should discuss which is most accurate at our next meeting. 

Additionally, the lowest values (ie. at 3370 ft) are causing MTOM to abort in certain scenarios because the 'remaining area' is less than zero. This is due to an internal calculation that calculates: RemainingAreaAvg = SurfaceAreaAvg - RiverAreaAvg - StreamsideAreaAvg - TerraceAreaAvg, which would be less than zero at 3370 ft. 

![ElevationArea](https://user-images.githubusercontent.com/18153871/108119792-8a549300-705d-11eb-8a64-c8fda7bfc744.PNG)

**Comment by hpatno** [comment]
Thanks for posting this Sarah. It looks like the way CRSS handles surface area below bypass tube and deadpool is the right way to move forward.

**Comment by sbaker2423** [comment]
Great - thanks for the input, Heather! We can work on moving that table into MTOM.

**Comment by sbaker2423** [comment]
Changes made to v9014 by Alex.
