### ISSUE TITLE
Negative Havasu Outflow seen in dev testing tool runs

### ISSUE THREAD

**Issue by sbaker2423** [usbr/MTOM#159]
A few dev testing tool runs initialize Powell and Mead at very low pool elevations and also have low hydrology input flows. During a few of these runs, Lake Havasu calculates a negative outflow since users above Havasu take more water than is available. Havasu's outflow is solved based on the input target storage with no checks for the mass balance. This is done in the function GetTargedStorage(). 

I compared the CRMMS logic to the CRSS logic and they differ slightly. CRSS checks to see if the outflow from the RuleCurveStorage() would result in a negative storage. If the outflow would not be negative, it sets the storage to the target. I propose trying to emulate what CRSS is doing, which would add extra checks on the outflow and hopefully solve this issue. I have not tried to implement this yet. CRMMS has a function with the same name as the CRSS function, but it does not perform the same checks as the CRSS function.

There was discussion how to handle use in the LB. At this time, CRSS assumes hydrologic priority. I'd assume we'd do the same for now. 

Note: this same logic is used at Mohave and would likely need to be updated there.

## CRMMS Logic:
![CRMMS_Havasu](https://user-images.githubusercontent.com/18153871/114750250-04795f00-9d11-11eb-94de-2ec6ee7017b0.PNG)

## CRSS Logic:
![CRSS_Havasu](https://user-images.githubusercontent.com/18153871/114750248-04795f00-9d11-11eb-8124-519b42a9ccca.PNG)

**Comment by rabutler-usbr** [comment]
Now at https://github.com/usbr/CRMMS/issues/27
