### ISSUE TITLE
MTOM rdf

### ISSUE THREAD

**Issue by cfelletter** [usbr/MTOM#16]
@rabutler-usbr I'm picking this again and using the latest rdf from April the RdfToExcel produces a xlsx file with only the header information without generating any error messages. 

RWPlyr gives me the error:
"Stopped reading at empty line 385 but text exists afterwards (discarded): units: m3" 

So I'm assuming this means something is wrong in the rdf.  I'm going to start by reformatting the control file unless you think otherwise.

**Comment by cfelletter** [comment]
Alright I've determined something in dummy.controlfile.txt is causing RW to produce corrupt rdf files but I haven't diagnosed the exact issues.When I use RdfToExcel the xlsx documents are never completed (excel says they are still open). I have been successful in extracting part of the file and generating readable rdfs so I'm going to proceed with making a new control.

**Comment by cfelletter** [comment]
@apivarnik or @clhorner I'm trying to create control file that will generate an rdf of outputs that matches whats included in MTOM_EnsembleOutput. There are a number of slots I cant find 
#FloodControl.FloodControlFlag
#PowellData.EqualizationCond
#PowellCarryoverVolume
#PowellTargetAnnualReleaseVolume
# SacWYType
# LIAbvLBDVTrigger
# PowellActualAnnualReleaseVolume
# EqualizationAbove823
# EqualizationAt823
# UpperBalancingAbove823
# UpperBalancingAt823
# UpperBalancingBelow823
# MidElevationReleaseAt823
# MidElevationReleaseAt748
# LowerBalancingAbove823
# LowerBalancingAt823
# LowerBalancingBelow823
# LBNormalCondition
# Step1ShortageFlag
# Step2ShortageFlag
# Step3ShortageFlag
# AnnualFloodControlFlag
# AnnualShortageAnyTypeFlag

**Comment by clhorner** [comment]
Do you mean that you can't find where they're located in the model, @cfelletter ? If so, you can open up the name map for the Excel_EnsembleOutput, and it will show you which slot each of those "nicknames" correspond to in the form object.slot. 

Let me know if you need more info.

**Comment by cfelletter** [comment]
@rabutler-usbr Would you review this before the meeting? Main file is RWDataPlyrExample_MTOM5Yr.R

**Comment by rabutler-usbr** [comment]
Nice work @cfelletter! I think this a great example of using RWDataPlyr. I committed a few changes to the R file, and made comments in your last commit of the R file for your consideration.

**Comment by apivarnik** [comment]
@cfelletter 

After testing the RDF capabilities we have some feedback:

1. In the system table csv file the values for surplus of any amount are actually the values for flood control
2. Changing the dates in the user input section for yrs2show, peYrs, yy5 in the MTOM compare code makes the entire code fail. 
3. We would like to configure a different comparison table for Powell. We would like to discuss this when you get the opportunity.

**Comment by cfelletter** [comment]
@apivarnik 
1. This was actually a question I had when putting the files together but had lost track of. If you know which slot is represents surplus in MTOM than we can update the information in MTOM_sys_rwa.csv for variable lbFcSurplus. I hadn't originally found slot like this in the model and if there isn't one we might want to create one since not having it will cause the code to error. 
2. This likely has to do with the run length but I'm not surprised the code isn't super robust. What years were you trying? 
3. Sure.

**Comment by cfelletter** [comment]
@apivarnik I was just able to run the code on my machine. Go a head commit that change to the MTOM sys csv file slot name and try to rerun it.
