### ISSUE TITLE
Add blank MTOM_EnsembleOutput.xlsm template to repository

### ISSUE THREAD

**Issue by rabutler-usbr** [usbr/MTOM#2]

**Comment by cfelletter** [comment]
Shouldn't there also be a Inflow Forecasts folder with a blank EnsembleForecast.xlsx? @clhorner

**Comment by clhorner** [comment]
The EnsembleForecast.xlsx pass through spreadsheet is generated by the CBRFC_EnsembleForecast.xlsm spreadsheet when you run it. @cfelletter
