### ISSUE TITLE
Minute 323 - Mexico Water Reserve

### ISSUE THREAD

**Issue by clhorner** [usbr/MTOM#20]
Need to switch ICMA references to Mexico Water Reserve per minute 323. This requires working with Water Accounting to ensure correct SDID's are being used in DMIs for these slots.

**Comment by apivarnik** [comment]
includes slots for annual creation, annual balance, and annual delivery

**Comment by cfelletter** [comment]
@gcaallan and @apivarnik in the future you can track commits related to this issue by adding` #20` to commits and when its do add `closes #20` to the final commit. We can always reopen and issue later if its found to have bugs.
