### ISSUE TITLE
SNWA DSS Delivery

### ISSUE THREAD

**Issue by gcaallan** [usbr/MTOM#22]
SNWA DSS delivery needs to be evaluated in shortage logic.

**Comment by apivarnik** [comment]
Should they be taking DSS in shortage up to full apportionment? Or should they leave the shortage volume in Lake Mead (when true demand is less than 287 kaf)?

**Comment by apivarnik** [comment]
Rule is modeling what we intend (updated in CA ICS update), but we still need to talk to SNWA for guidance

**Comment by stighi** [comment]
This will be addressed when we incorporate DCP logic and will be closed when DCP logic is completed.
