### ISSUE TITLE
Monthly distributions

### ISSUE THREAD

**Issue by apivarnik** [usbr/MTOM#26]
Review monthly distributions and where Monthly Percents table should be kept. It is currently in the shortage object

**Comment by rabutler-usbr** [comment]
@apivarnik I'll be interested in seeing what you come up with. In CRSS we have monthly distributions that can be different for normal, surplus, and shortage years (we should review this there).

**Comment by stighi** [comment]
Monthly distributions for most water users are based on a proportion from their schedule provided to Water Accounting.
River Ops and Water Accounting have coordinated on out-year monthly distributions for Mexico schedules
