### ISSUE TITLE
MWD ICS Demand Variability

### ISSUE THREAD

**Issue by apivarnik** [usbr/MTOM#29]
MWD ICS demand variability in year 1 of the run in months other than January?

We currently allow for CAP and SNWA demand variability in months (all months or specific months?-need to consult stakeholders) other than January - but not MWD or Ag users below Parker

**Comment by stighi** [comment]
@apivarnik I think the California ICS work you completed addresses this item for MWD. The next step is to check out the hydrologic LB demand variability for the below-Parker ad users.

**Comment by stighi** [comment]
I just realized there was a separate issue created for the Ag users below Parker. The resolution for MWD is to have the ICS-demand variability run January through March for the first year (and the outyears). April-December of the start year we will go with MWD's operational schedule.
