### ISSUE TITLE
Dynamic State Adjusted Apportionment - AZ, NV

### ISSUE THREAD

**Issue by apivarnik** [usbr/MTOM#32]
Dynamic state adjusted apportionments for AZ and NV? (similar to CA)

for consideration, not committed to making this change

**Comment by stighi** [comment]
This is a critical bug now with DCP. Model currently uses 24MS adjusted apportionments which causes the model to always model DCP schedules as om the 24MS and doesn't allow for dynamic schedules for various DCP levels in the traces.

**Comment by apivarnik** [comment]
@stighi DCP bug addressed in #107. The rest of the issue still needs to be addressed

**Comment by rabutler-usbr** [comment]
Now at https://github.com/usbr/CRMMS/issues/12
