### ISSUE TITLE
RiverWare Accounts

### ISSUE THREAD

**Issue by apivarnik** [usbr/MTOM#45]
Write up for Reclamation management on RiverWare accounts - objectives and how accounts can help us meet our objectives. 

Goal: get buy-in to move forward with development of "accounts" in RiverWare .

Long term goal, no immediate action needed from Dev team

**Comment by stighi** [comment]
Per the discussion with the CRSS and CRMMS dev teams and CADSWES on 5/19/21, it does not appear that adding RiverWare Accounting will be helpful in the Colorado River Basin models.
