### ISSUE TITLE
LC to Run Sarah's Verification Model Operationally

### ISSUE THREAD

**Issue by cfelletter** [usbr/MTOM#50]
Sarah has cleared the data out of the model to setup her run. LC should run the model operationally with all the correct linking to HDB and ensure that model runs and results are same as Alex's June.

**Comment by sbaker2423** [comment]
LC ran model and found these issues which were changed in the testbed model and merged to the dev branch:
DMI Edits
1.	Add data slots for AnnualCreationEC_AZ and Annual Delivery_SysEff_NV to HDB to Riverware Input DMI (LC Yearly Data – ICS inputs Dataset)
2.	 Add Historic Data Flaming Gorge to DMI (UC Historical – UC Historical Inflow Dataset)
3.	Add Historic Data Yampa at Deerlodge to DMI (UC Historical – UC Local Flowpoints Dataset)

Initialization Rule Edits
4.	Change Finish Timestep in the new Yampa/Flaming Gorge initialization rule to “StartTimestep -1” from “StartTimestep – 13”
5.	Change the monthlypreviousyearslots function in the initialization ruleset to the following (delete un-necessary slots; Note- It was the Paria River Local Inflow slot being set to Output that caused the initialization rule to fail)
