### ISSUE TITLE
Should dummycontrol.txt be empty?

### ISSUE THREAD

**Issue by rabutler-usbr** [usbr/MTOM#57]
Now that @cfelletter created output.control, is dummycontrol.txt necessary? 

Suggest deleting it. 

It may also be nice to have a NoOutput.control file to use if you do not want to create rdf files. @sbaker2423 might already have this.

**Comment by sbaker2423** [comment]
I've made a NoOutput.controlfile.txt (empty file) for my uses and could add to the file.

**Comment by rabutler-usbr** [comment]
I think it would be useful to have that in the repository, @sbaker2423 

As a side note, the control files are just plain text files so the .txt extension is fine. In CRSS we use a .control extension to help us know that's what they are. It might be good to standardize that between the two models.

**Comment by sbaker2423** [comment]
@rabutler-usbr  Sounds good. Next time I make changes to the dev branch I will make this change and delete the dummycontrol.txt since it looks like it is not used in MTOM.

**Comment by stighi** [comment]
I can confirm, the dummy control file is an empty file, from when we were not creating rdf output. It has, for operational runs, been replaced with the output control file @cfelletter created. I agree with @sbaker2423 and @rabutler-usbr, if we need an alternative empty control file, the renamed NoOutput file sounds good to me too.
