### ISSUE TITLE
Update model (and ruleset?) to current March 2018 

### ISSUE THREAD

**Issue by cfelletter** [usbr/MTOM#6]
The model on the dev branch is the January model last saved by @apivarnik on 1/19. We should replace this with the latest version of the model. Same goes for the ruleset. Since this was just an oversight we could pretend it was a patch and update the version name to V1.0.1

**Comment by cfelletter** [comment]
If updating the ruleset we could also take the opportunity to unzip the ruleset and close issue #1

**Comment by stighi** [comment]
The January model is the last official, publicly posted model package. I would think you'd need to have both the January (official public) version and the March (development/monthly) version? Perhaps in different branches though, is that what you mean?

**Comment by cfelletter** [comment]
@stighi I had forgotten about this distinction. I believe the decision was to have the Master branch contain the latest public version and the dev branch to contain the Master and the latest monthly release, correct? 

What had confused me was how we have the directory setup. MTOM_Rules_V1.0.0_201803.mdl, the January official, is in the RW Files folder and MTOM_Rules_V1.0.1_201803.rls, the model used for the March run, is in _MAR18 folder. I think both models should be in the RW Files folder with either a note in the change log or elsewhere about what each model represents. I will incorperate this change into my suggested reorginzation of the tracked folders #7 

We should also start using tags for each monthly model. I went ahead and tagged Alan's initial commit of the January model as 'Jan2018Offical.' Monthly models could be tagged 'Mar2018.'
