### ISSUE TITLE
Generic R Script

### ISSUE THREAD

**Issue by cfelletter** [usbr/MTOM#60]
Mantra:  ggplot is useful for simple things and for things your have to do over and over again. For everything else (complicated, single/minimal use) there is excel. 

Input: 
Rdf Name
Rdf location
Object.Slot
Time Period
Time Filter (filter our months or years)
Axis Titles & Plot Title
Plot Note, etc

Choose Plot Type, I'd like to support 
Trace Mean
Trace Box Plot at Monthly or Yearly 
% Exceedance Plot 

Additional Features
Comparison of two scenarios or just one run
Addition of custom horizontal lines (e.g. Max PE) or vertical lines (e.g. after 2026) 
Second y-axis same scaling (e.g. Imperial/Metric or acftmo / cfs)

A additional script might make multi slot plots with second y-axis w/ different scaling (e.g. Outflow + PE)

Output
One jpeg
Image Size
Output Folder

My goal would be to turn this user friendly tool over to UC/LC for their use.

**Comment by cfelletter** [comment]
@rabutler-usbr says: I think this is a great idea, but definitely not trivial. 

I think the tough part is determining how "good" with R they need to be. On one end, you could abstract out as much of the real R code to other functions/files and allow them to only change things in a ui.R file. On the other end, you could provide three generic functions for the three plots they want to be able to make, and then they could build their own R-scripts by using those three functions over and over again. It may make sense to talk it over with them to see what they are comfortable with. 

Either way- if it's going to be generic and work for people that are not super familiar with R, it needs to "fail-fast". 

I recommend checking out the asserthat package - that's a nice way to check expectations. ex: in this instances you might expect that rdf is a character of length 1- it should fail if it's not. That will make it easier for them to figure out what's going on, if things aren't working for them.

**Comment by cfelletter** [comment]
My idea (at least for now) is that the latter: three generic functions for the three plots they want to be able to make, and then they could build their own R-scripts by using those three functions over and over again. Rather than make functions I'm keeping the code in a script for now with comments so that users can understand whats going on under the hood and possibly modify it.

**Comment by rabutler-usbr** [comment]
RWDataPlyr v0.6.1 includes `read_rwd_agg()` to make reading those files in a little easier.

**Comment by cfelletter** [comment]
Thanks. 

https://www.r-project.org/nosvn/pandoc/assertthat.html for ideas on error messages

**Comment by cfelletter** [comment]
This has been replaced by https://github.com/usbr/Process-MTOM-R
