### ISSUE TITLE
Save exhibit run (8.23 maf) reservoir output 

### ISSUE THREAD

**Issue by sbaker2423** [usbr/MTOM#69]
It would be useful to store Powell and Mead reservoir output after Powell calculates operations with an 8.23 MAF release. This is sometimes referred to as an exhibit run and would allow us to more easily check if Powell and Mead are solving correctly. The important slots would be pool elevation, storage, and possibly outflow for the key months of September and December (but likely all months would be saved due to slot constraints).  -Discussed 10/9/18

**Comment by cfelletter** [comment]
Is this still live @sbaker2423 ?

**Comment by sbaker2423** [comment]
@cfelletter  Not sure... it is still a potential enhancement, but we havent discussed it in a while. It could help with debugging the model if we ever decided to implement it.

**Comment by sbaker2423** [comment]
closing because we are moving to CRMMS repo and it doesnt seem likely for this enhancement to be implemented.
