### ISSUE TITLE
24-Month Study - MTOM Integrate into 1 model

### ISSUE THREAD

**Issue by stighi** [usbr/MTOM#73]
Consider how we might integrate 24MS and MTOM so there is only 1 model. Would likely require scripts that load one ruleset or another, set slots to output or input as appropriate, and run one set of initialization DMIs or another. Longer term goal.

**Comment by hpatno** [comment]
Woohoo! Enhancements completed and part of operations. Great job Shana!
________________________________
From: Shana Tighi ***@***.***>
Sent: Monday, May 24, 2021 4:19 PM
To: usbr/MTOM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] Re: [usbr/MTOM] 24-Month Study - MTOM Integrate into 1 model (#73)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Closed #73<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fusbr%2FMTOM%2Fissues%2F73&data=04%7C01%7Chpatno%40usbr.gov%7C9af664dc0acf491c84f908d91f0204ee%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637574915801838999%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qs4%2FPxSTRJ%2Bc%2BTEh80QnUlDZJOE1TspjDA9mLn0%2BY%2BQ%3D&reserved=0>.
