### ISSUE TITLE
Running MTOM w User Input

### ISSUE THREAD

**Issue by cfelletter** [usbr/MTOM#81]
I was able to run MTOM successfully in rule based simulation mode after changing outflow slots to user input for a number of the reservoirs (see below). This is not the case for all reservoir outflow but I have a few ideas why including execution constraints and more interrelated rules. I certainly think it could be developed once we get buy in. 

**Works**
Blue Mesa  
Morrow Point
Taylor Park
Fontenelle
Navajo

**Fails**
Flaming Gorge
Vallecito
Powell

Execute Constraints
If Not IsInput()
or 
Is NaN() 
for all MTOM rules. 

**To Do** 

- [ ] Developing a list of all the possible input.

- [ ] Explore IsInput() or IsNAN() use in rules.

**Comment by cfelletter** [comment]
@sbaker2423 : A note on Powell - if you want to set the outflow you really need to set the Target Annual Release Volume. This is what controls Powell's releases. MTOM should already be set up so an operator could input Powell's operations.

**Comment by rabutler-usbr** [comment]
I'm not sure if MTOM has any rules that are expected iterate/execute multiple times, but `IsNaN()` will prevent that from happening. I would advocate for `Not IsInput()` as I think that makes it more clear why the rule would be skipped. 

We should also think about developing a list of all the possible input. Is it only reservoir.Outflow? and Target Annual Release Volume, or are there other things that could also be input?

**Comment by sbaker2423** [comment]
I agree that we should document the possible input slots. In general, this would be allow one to run MTOM more easily if they aren't aware of how these slots are associated with the rules. 

For Powell, there are other slots to manually set the release/tier/branch/minTARV. When I was implementing hindcast mode in MTOM, I know I had some issues associated with using `IsInput()` or `IsNaN()`. I can't really remember if the issues were only at Powell or were at other reservoirs. I could look back through my commits to see...

**Comment by sbaker2423** [comment]
By the way, I think this lends itself to Issue #73

**Comment by cfelletter** [comment]
Agreed. I didn't see #73 when I made this. We can merge them or keep them separate according to the discussion at tomorrows meeting.
