### ISSUE TITLE
Test full extent of reservoir operating range for MTOM Development

### ISSUE THREAD

**Issue by cfelletter** [usbr/MTOM#84]
Develop a way to stress model model rules to verify development work for all start months, forecast hydrologies, and initial conditions. 

Initial Vision:
Riversmart Study runs MTOM with custom select initial conditions and forecasts (DMIs) starting in each month Jan-Dec. If MTOM solves for all runs/timesteps it passes. 

To Do

- [x] What forecasts? 

- [x] What ICs?

**Comment by rabutler-usbr** [comment]
We need a process to test MTOM development changes using multiple initial conditions and multiple starting elevations. 

Key questions:

- do we need any new RiverWare sctipts?
- should we use the TestBed or develop a new RiverSMART study file for this?
- should we initialize model in future or historical?
- which starting conditions do we want to test?

Step 2 (#89 ) will be automated and semi-automated post processing tests.

**Comment by sbaker2423** [comment]
This work has been completed and is in internal test. Files are located in the RW/DevTestingTool_Files folder.

**Comment by sbaker2423** [comment]
development testing tool was created.
