### ISSUE TITLE
Verify Crystal elevation

### ISSUE THREAD

**Issue by rabutler-usbr** [usbr/MTOM#91]
The last two MTOM runs have included this note in the summary: 

> Crystal Reservoir has a different target pool elevation in 24 MS (6,753 ft) and MTOM (6,745 ft). Should MTOM be updated?

@cfelletter could you look into this?

**Comment by cfelletter** [comment]
Rick recommends 6753.04. I'd be fine with pushing this into MTOM but I'd like to resolve the negative MP release issue in CRSS at the same time. @rabutler-usbr have you had time to think on this? When we do so we might want to update the logic in both models to handle when the t-1 reservoir elevation is less than the target. Currently the rule 'Set Morrow Point and Crystal Storage' sets both to a target elevation in all timesteps which could cause negative outflows in the PE falls below the target. 

RC, 20171228: Crystal, the lip of the ungated spillway is 6756 feet so this is roughly 3 feet of cushion in Crystal and this is about 900 acre-feet of storage space.

**Comment by cfelletter** [comment]
@apivarnik I know we weren't planning on updating MTOM for April but if CRSS gets updated for Aspinall would you guys be okay with an update?

**Comment by cfelletter** [comment]
Things to Modify

MTOM
- [ ]   'Set Morrow Point and Crystal Storage' to constant targets and fire in all timesteps
- [ ]  TargetHW fct with 1-3 policies to match CRSS
- [ ]  BlueMesaOutflowCalc Max/Min Constraints
- [ ] High priority prevent 0 outfow rule

CRSS
- [ ]  TargetHW fct gains fix
- [ ] High priority prevent 0 outfow rule

**Comment by apivarnik** [comment]
@cfelletter Whether we make an update to MTOM for the April run is a @stighi / @rabutler-usbr  decision

**Comment by cfelletter** [comment]
Okay I'm fine with no updates. This is a rule change note a simple slot modification since the current MTOM rules use the [t-1] storage not a target elevation. @apivarnik I'll update the team at our next meeting about future updates based on @rabutler-usbr and I's discussion today.

**Comment by stighi** [comment]
I looked at the rule that sets Crystal storage, and was surprised to find that the logic simply sets the storage at time t to the storage at time t-1. It isn't using a guide curve or target storage! It sounds like we may need to change this logic going forward?
![image](https://user-images.githubusercontent.com/12956929/55502402-560a9180-5601-11e9-94e5-4e370269040f.png)

**Comment by rabutler-usbr** [comment]
Agreed @stighi! 

We spent two hours going over Aspinall in CRSS today. I think this approach generally works in MTOM since there is no evap at Crystal or Morrow Point (another question), and there are intervening gains above each reservoir. However, I think the rules still need to be able to "recover" to the target storage when they start above/below the target, which is the likely reason that Crystal's elevation has been off these last few runs. 

We'd like to get Aspinall updated in CRSS first, and then move the changes into MTOM, though it won't occur until after the April run. Does that sound ok?

**Comment by cfelletter** [comment]
I've created a new version of the CRSS rules that incorporates BM releasing to meet a MP target elevation. We can try to move these CRSS changes into MTOM in the next few development cycles.   For now CR will just maintain it's t-1 storage since but we could take this topic up in the future. I think a more complete review of this rules should happen down the road when resources (aka me) free up.

**Comment by cfelletter** [comment]
@rabutler-usbr & @stighi I think this is almost done but i'm noticing that in June the model doesn't EstimateEvaporation function doesn't calculate the correct value which leads the reservoir to fall slightly below its target. I've look at this function and have no idea why for this one month it wouldn't work. I suspect maybe its a unit's issue but this doesn't occur in other non-31 day months (e.g. Feb). This also doesn't occur in CRSS. The total departure is ~0.01 ft. Any thoughts from your experience on what might be causing this? Otherwise I could take the issue to CADSWES.

**Comment by cfelletter** [comment]
Previously ID’d updates
BlueMesaOutflowCalc 
- [ ]  BlueMesaOutflowCalc reference BaseCanyonTargetFlows[@t,H Class].  - done in dev
- [ ]  BlueMesaOutflowCalc reference 7487.90000000 "feet" to SpillwayElevation[] - done in dev
- [ ]  Change old TP 9/22/2015 comment in BlueMesaOutflowCalc and Set Release Control Indicator to "CF: If the inflow + storage[t-1] is not equal to the guide storage[t] then will calculate a negative outflow, setting to 0 prevents that from being included in solving the Blue Mesa Outflow"  - done in dev

Updates to match CRSS
UBRuleCurveData.ReservoirData
minRelease BM: 270 to 0 cfs
minRelease CR: 300 to 0 cfs
maxRelease BM 32770 MP 41000 CR 41350
CF,20190403: Aspinall updated to match CRSS based on discussion with Rick Clayton. 
BlueMesaData.StorageTargets 
Rules: Crystal Outflow, Morrow Point Outflow (but currently no evap)
Fct: UBConstrainedOutflow()
UBRuleCurveData.ReservoirData DeadCapacity 
Delete Rules: Set Morrow Point and Crystal Storage, Set Release Control Indicator 
Add monthly evap method to MP and CR. CRSS uses an Input Evaporation with Initialization Rules but MTOM has Monthly Evap.
Update MP and CR Outflow rules to account for evap and match CRSS
Update SolveBlueMesaReleaseForDownstreamTargets() and SolveBlueMesaReleaseForCrystalReleaseTarget() to account for evap and match CRSS

Results
A run of the modified model (“AspDev”) was completed and the results were compared to the official MTOM run for April 2019 (“AprOffc”). 

Minimum Monthly Flows The official model calculated a 0 release for BM in nine timesteps. The dev model had no releases less than or equal to 0 for BM. 

MRM 

BlueMesa.Outflow
Minor shifts, lower May higher July release.   
 
BlueMesa.Pool Elevation
Minor shifts between months and how often meets its PE targets.  
 
MorrowPoint.Pool Elevation
New rules maintain the target MP.PE. 

June Evap Issue
In June the model doesn't EstimateEvaporation function doesn't calculate the correct value which leads the reservoir to fall slightly below its target. I've look at this function and have no idea why for this one month it wouldn't work. I suspect maybe its a unit's issue but this doesn't occur in other non-31 day months (e.g. Feb). This also doesn't occur in CRSS. The total departure is ~0.01 ft. 

MorrowPoint.Outflow
Same as Blue Mesa. 

Crystal.Pool Elevation
New rules maintain the target CR.PE. 

Crystal.Outflow
Same as Blue Mesa. 

GunnisonNearGrandJunction.Outflow
Hardly any impact on Whitewater target. 
 
Powell.Inflow (2019-2026) 
The effect on Powell inflow is negligible overall.  

Final Model and Ruleset
MTOM_V2.3.201904.9000
MTOM_Rules_V2.4.9000.rls
