### ISSUE TITLE
Review FG DaysAtBypass

### ISSUE THREAD

**Issue by cfelletter** [usbr/MTOM#94]
After Spring Ops review with @hpatno and Beau

Speaking with Beau and reviewing the ROD it seems like the DaysAtBypass is "overly generous" for at least the average year. Beau said 7 days on average and 14 once every ~4 yrs. EIS says 14 every 3 years. Currently this value is set to be between 7-21 days based on if the exceedance interpolating between 0.4 and 0.6.

**Comment by hpatno** [comment]
Hey Conor, can you fill me in on what you've assigned me to do?
________________________________

**Comment by cfelletter** [comment]
I believe if you click the link it explains pretty well:
Speaking with Beau and reviewing the ROD it seems like the DaysAtBypass is "overly generous" for at least the average year. Beau said 7 days on average and 14 once every ~4 yrs. EIS says 14 every 3 years. Currently this value is set to be between 7-21 days based on if the exceedance interpolating between 0.4 and 0.6.
This isn’t a priority I just am going through open MTOM issues and trying to see if there is anything that can be closed or has fallen by the wayside. This is just not a call I feel like I can make and would like your expertise before we start going in a changing things.

Happy Thursday

**Comment by cfelletter** [comment]
CRSS and MTOM match for this. MTOM's days at bypass increased to match CRSS.
